import { Ubuntu, Lobster } from 'next/font/google'
import './globals.css'

const ubuntu = Ubuntu({
subsets: ['latin'],
weight: ['300', '400', '500', '700'],
variable: ['--font-ubuntu'],
display: 'swap',})

const lobster = Lobster({
  subsets: ['latin'],
  variable: ['--font-lobster'],
  weight: '400',
  display: 'swap',
})

export const metadata = {
  title: 'Ground Transport Concierge Singapore',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${ubuntu.variable} ${lobster.variable}`}>{children}</body>
    </html>
  )
}
